version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install libgmp-dev
            sudo apt-get install libmpfr-dev
            sudo apt-get install libmpc-dev
            python -m pip install --upgrade pip
            make environment
      - run:
          name: Install Modules
          command: |
            make install validate
      - run:
          name: Lint
          command: |
            make lint
      - run:
          name: Test
          command: |
            export PYTHONUNBUFFERED=1
            make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
